{% set name = "intake-duckdb" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intake/intake-duckdb/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0fb6685ed81a9602abf4f7d7867315f9ea469a0a095203b1bfbd6e9d3105467e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-git-versioning
    - pip
  run:
    - python >=3.8
    - intake
    - pandas
    - python-duckdb

test:
  imports:
    - intake_duckdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intake/intake-duckdb
  summary: DuckDB plugin for Intake
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blakerosenthal
