{% set name = "intake-duckdb" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intake/intake-duckdb/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8f212b16d7a156574175fe5e6762c3179b986f1684aa95573dd7198c7567ea2f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-git-versioning
    - pip
  run:
    - python >=3.8
    - intake
    - pandas
    - python-duckdb

test:
  imports:
    - intake_duckdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intake/intake-duckdb
  summary: DuckDB plugin for Intake
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blakerosenthal
